name: Build Windows EXE

on: [push] # Se lance à chaque fois que vous faites un 'git push'

jobs:
  build:
    runs-on: windows-latest # On utilise un vrai Windows !

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Graphviz (Binaire Windows)
      run: choco install graphviz -y

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6 pyinstaller
        # Ajoutez ici vos autres bibliothèques (ex: pip install pandas)
        if (Test-Path requirements.txt) { pip install -r requirements.txt }

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --windowed --add-binary "C:/Program Files/Graphviz/bin/*;graphviz_bin" interface.py
      # Note : L'option --add-binary aide à inclure Graphviz si votre code le cherche localement

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: MonApplicationWindows
        path: dist/interface.exe
